spring:
  datasource:
    url: jdbc:postgresql://ingela.com/ingela_access
    username: ingela
    password: Reme6502tva#
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    show-sql: true
    #database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    #org.springframework: DEBUG